### ISSUE TITLE
Student Update Form

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#20] opened 2019-02-08 03:28 UTC
Student update form in views needs to be made

**Comment by brosekerg** [comment] 2019-02-11 15:42
can i do this one?

**Comment by smattingly** [comment] 2019-02-11 16:27
@brosekerg I see that you self-assigned this. Only managers may assign tasks-- in this case @tydingsl. Even if the manager has communicated the Issue is yours, the manager makes the assignment in GitHub. Also, the discussion like "Can I have this one?" should happen in the team discussion thread for that purpose, not on the Issue itself. Please respond with an "OK" (or questions) so I know you've seen this.

**Comment by brosekerg** [comment] 2019-02-15 15:08
OK

**Comment by smattingly** [comment] 2019-02-15 15:22
@tydingsl @brosekerg This form is in place, and I'm not aware of anything that needs to be done with it. Lauren, if you agree please close it; otherwise please clarify what needs doen.

**Closed** 2019-02-15 15:33 UTC
