### ISSUE TITLE
Visit Model

### ISSUE THREAD

**Issue by tydingsl** [dewv/nlcAttendance#33] opened 2019-02-13 02:36 UTC
using CONTRIBUTING.md, create the model file for Visits (the login and logout model)

**Comment by codybroyles** [comment] 2019-02-13 05:01
🍅

**Comment by codybroyles** [comment] 2019-02-13 05:03
@ricardmc99 I created the Visit model and put a pull request into your branch. Please Inform me if any changes need to be made.

**Comment by codybroyles** [comment] 2019-02-13 21:57
🍅

**Comment by codybroyles** [comment] 2019-02-16 23:41
🍅 🍅

**Comment by codybroyles** [comment] 2019-02-16 23:43
Model is near completion, having issues with the checkIn and checkOut times

**Comment by codybroyles** [comment] 2019-02-18 16:02
🍅

**Comment by codybroyles** [comment] 2019-02-18 16:27
@ricardmc99 see branch Issue33_22_23 for our merged work.

**Comment by codybroyles** [comment] 2019-02-18 16:27
🍅

**Comment by codybroyles** [comment] 2019-02-20 02:01
🍅

**Comment by codybroyles** [comment] 2019-02-20 02:50
🍅

**Comment by codybroyles** [comment] 2019-02-20 03:10
🍅

**Comment by codybroyles** [comment] 2019-02-20 03:56
🍅

**Comment by codybroyles** [comment] 2019-02-20 04:55
🍅

**Comment by codybroyles** [comment] 2019-02-20 04:57
Currently working on testing the functionality of the model and its lifecycle call back function `beforeUpdate()`.

**Comment by codybroyles** [comment] 2019-02-20 17:03
🍅

**Comment by codybroyles** [comment] 2019-02-20 17:24
@smattingly I am getting the following error when attempting to run the test code. 

```
TypeError: Date.getMinutes is not a constructor
      at newConstructor.postPopulate (api/models/Visit.js:6:684)
      at Context.<anonymous> (test/models/_visit.js:69:43)
```
Any ideas as to why we would be having issues calling the global Date class?

**Comment by codybroyles** [comment] 2019-02-20 17:32
🍅

**Comment by smattingly** [comment] 2019-02-21 02:27
Would be helpful if I knew what branch/where to see the actual code. I suspect you have something like `new Date.now()` and `new Date.getMinutes()` when you need `new Date().now()` or maybe even `(new Date()).now()`. In other words, you want to call the `Date` constructor and then call `now` on the new object; instead you are calling the nonexistent constructor for class `Date.now`.

**Comment by codybroyles** [comment] 2019-02-21 03:44
Ok, the branch is Issue#33-VisitModel just for reference. My code was as you described, I attempted your solutions but both failed. I was able to solve the issue by using the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) for Date.
Thanks.

**Comment by codybroyles** [comment] 2019-02-21 03:44
🍅

**Comment by codybroyles** [comment] 2019-02-21 04:12
🍅

**Comment by smattingly** [comment] 2019-02-21 16:32
Looking at the model attributes, I think we are on slightly different pages. Also I think that there is a slightly simpler way than what I had in mind. 
1. `visitLength` and `estimatedDuration` appear to be redundant. Suggest eliminating the second one.
2. There has always been a field that indicated if the visit length was estimated or not. Suggest a boolean named `isLengthEstimated` that defaults to `false`.
3. Further suggestion: have your `afterPopulateOne` (formerly known as `postPopulate`) set `isLengthEstimated` to `true` when appropriate. This can be the flag that other code checks to see how to behave. That's slightly bending the meaning, but I like it better than the alternative of "decorating" the record with a temporary additional flag that is not stored in the database.

**Comment by codybroyles** [comment] 2019-02-21 17:47
🍅    Made the suggested changes.

**Comment by codybroyles** [comment] 2019-02-22 16:20
smattingly: testing visitLength, create a few records and modify the checkin time via update.

**Comment by codybroyles** [comment] 2019-02-25 15:09
🍅

**Comment by codybroyles** [comment] 2019-02-25 15:50
🍅

**Comment by codybroyles** [comment] 2019-02-25 16:38
🍅

**Comment by codybroyles** [comment] 2019-02-26 15:30
🍅  I believe this is close to wrapping up, I will continue working with @ricardmc99 to have it hooked in to the views.

**Comment by codybroyles** [comment] 2019-02-26 15:48
🍅

**Comment by codybroyles** [comment] 2019-02-26 17:13
🍅

**Comment by codybroyles** [comment] 2019-02-28 17:43
🍅 

@smattingly I worked today to get my test coverage to above 95% and my work is now 100% covered, I dug down to see what is not being covered specifically and it is specifically 3 helpers keeping my branch from passing the 95%; get-domains.js, populate-one.js, and response-view-safely.js. It seems there are a few 'branches' and statements that arent covered. Are there test not pushed into master some where that would cover these or would it be a example of something we could flag?

**Comment by smattingly** [comment] 2019-02-28 21:23
@codybroyles There may be some candidates for ignoring for coverage here. But first, let's make sure everything else is in order. I meant for the helper integration tests to be called from each model's test file. (see Student model for example.) The helpers that are tested there take a model as an input argument-- in an OO design the would be model methods. I think that testing them with your model might boost the helper coverage.

**Comment by codybroyles** [comment] 2019-03-01 00:43
Ok

**Comment by codybroyles** [comment] 2019-03-01 15:38
🍅

**Comment by codybroyles** [comment] 2019-03-01 16:04
🍅

**Comment by codybroyles** [comment] 2019-03-22 15:18
🍅

**Comment by codybroyles** [comment] 2019-03-22 15:24
@smattingly We discussed in class a issue in the generic test code in the helpers causing a test to fail. I believe this is do to the epoch number in milliseconds being compared, you mentioned floating point comparisons. Below is the code in question.

``` Test Results 
1) Visit model
       Standard tests of model, helpers integration
         `populateOne` helper
           should return a data record for the specified ID, with all associations populated:

      AssertionError: expected 2018-01-01 01:01:01.000 -0000 to be 2018-01-01 01:01:01.000 -0000
      + expected - actual


      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/models/_helpers.js:87:49)
      at processTicksAndRejections (internal/process/next_tick.js:81:5)
```
``` test/models/_helpers.js
context("`populateOne` helper", function() {
            it("should return a data record for the specified ID, with all associations populated", async function() {
                let model = sails.models[modelName];
                let id = testData.record.id;
                let result = await sails.helpers.populateOne(model, id);
                result.should.not.be.an.Error();
                result.should.be.an.Object();
                should.exist(result.id, "The record returned by `populateOne` has no `id` property");
                result.id.should.be.a.Number();
                result.id.should.equal(id, `The record returned by \`populateOne\` has \`id\` ${result.id} but should have \`id\` ${id}`);
                for (let property in model.attributes) {
                    should(result[property]).not.be.undefined(); //result[property], `The record returned by \`populateOne\` has no \`${property}\` property`);
                    if (sails.helpers.isAssociation(model, property)) {
                        if (result[property] !== null) result[property].should.be.an.Object();
                        for (let associatedProperty in result[property]) {
                            result[property][associatedProperty].should.equal(testData.associations[property][associatedProperty]);
                        }
                    }
                    else {
                        result[property].should.equal(testData.record[property]);
                    }
                }
            });
```

**Comment by smattingly** [comment] 2019-03-22 17:11
I just pushed a change to resolve the problem with `Date` comparisons. 
FYI, that uncovered another test failure: your `convertToHours` helper appears to be returning values as type `string`. Take a look at one of the other helpers-- there is a special syntax for returning helper values that you are not using, and that may be the cause.

**Comment by codybroyles** [comment] 2019-03-25 13:57
🍅

**Comment by codybroyles** [comment] 2019-03-25 16:29
🍅

**Comment by codybroyles** [comment] 2019-03-25 16:57
🍅  I have all my test passing.

**Comment by codybroyles** [comment] 2019-03-27 03:36
:tomato:

**Comment by codybroyles** [comment] 2019-03-27 04:24
🍅

**Comment by codybroyles** [comment] 2019-03-27 04:58
🍅

**Comment by codybroyles** [comment] 2019-03-27 06:14
🍅

**Comment by codybroyles** [comment] 2019-03-27 13:34
@smattingly I was able to add the query code into [isAuthorized.js](https://github.com/dewv/nlcAttendance/blob/Issue33_22_23/api/policies/isAuthorized.js) in the combined visit repo [Issue33_22_23](https://github.com/dewv/nlcAttendance/blob/Issue33_22_23). I got the query to work and the sorting to work, but i cant seem to get that data stored outside the query. the visit variable has the most recent visit data at line 71 but is undefined at lines 73 and 76.

**Comment by codybroyles** [comment] 2019-03-28 16:31
🍅

**Comment by codybroyles** [comment] 2019-03-28 16:53
🍅

**Comment by codybroyles** [comment] 2019-03-31 17:10
🍅  @smattingly I was able to use null by changing the column type to datetime and data type to string. Everything seems to be working the same except that spam errors about records having the wrong "data type" happen when launching sails/test not sure what to address as my model test are still passing.

**Comment by codybroyles** [comment] 2019-04-03 14:22
🍅

**Comment by tydingsl** [comment] 2019-04-03 14:30
@codybroyles Can I get a progress update?

**Comment by codybroyles** [comment] 2019-04-03 15:19
@tydingsl I am working on what format time values are and how we store time values in the database. Prof Mattingly has provided me with the login code and policies implemented so I am working on connecting into them as well.

**Comment by smattingly** [comment] 2019-04-03 19:27
@codybroyles I used a new, bare sails app to experiment and I am getting (close enough to) the behavior I would like with the settings shown. As long as that approach is compatible with what you are/need to do elsewhere, I think that should clear things up.
![image](https://user-images.githubusercontent.com/21227171/55506932-9af3ef80-5624-11e9-8f95-41c688be357b.png)
The two data properties are commented out so that they will used the default values. This gets both an SQL `NULL` into the database for check out, and a JS `null` when you fetch that data. Uncommenting those lines works, too, it just overrides the defaults.

**Comment by codybroyles** [comment] 2019-04-04 00:15
@smattingly With the settings above, we still see the console messages although functionally it seems to work.

**Comment by codybroyles** [comment] 2019-04-05 17:06
🍅 🍅

**Comment by codybroyles** [comment] 2019-04-08 21:05
🍅

**Comment by codybroyles** [comment] 2019-04-10 15:03
:tomato:

**Comment by codybroyles** [comment] 2019-04-10 15:03
🍅

**Comment by smattingly** [comment] 2019-04-11 21:22
@codybroyles I tried moving policy logic into a controller, so that responses to requests were "flexible" without resorting to HTTP redirects. Got it working, but it ends up "faking" requests in a way that will make it difficult to know we have everything right. Much safer to stick with redirects, so it may as well stay in the policy. 
But, I did find the "routing" problem. I had added the condition to allow a checked out student to POST the check in form; but not one to allow checked in student to POST the check out form. I have fixed that in [latest commit](https://github.com/dewv/nlcAttendance/commit/12b9764977853a798a3a780dc75fca3142791280).

**Comment by codybroyles** [comment] 2019-04-12 01:54
@smattingly The idea of calculating the visit length when the form is being loaded was to use that check to determine if the student needs to estimate their visit length. I assume I could change the logic some and still do this calculation but, it seems that would only be a copy of the same code happening in your suggested addition.

**Comment by codybroyles** [comment] 2019-04-12 03:00
🍅    I am will have the suggested changes for tomorrows meeting. We can look over them then.

**Comment by codybroyles** [comment] 2019-04-12 03:32
🍅 New additions added and the records are now being fully updated.

**Comment by codybroyles** [comment] 2019-04-12 14:49
🍅

**Comment by codybroyles** [comment] 2019-04-12 14:50
Now working on getting test coverage to passing levels.

**Comment by codybroyles** [comment] 2019-04-12 16:22
🍅

**Comment by codybroyles** [comment] 2019-04-12 17:37
🍅 🍅  @smattingly I have added test coverage for the new additions to the Visit model and will be doing documentation soon. I also cleaned up the test file for the Student model and added the profile update test to the staff file (which hasn't been converted to the bootstrap test data). Currently, there is a heavy lack of coverage for the policies and the staff model has a function not being tested that I'm not sure how to address. It is covered in the student model but the student model and staff model test are the same.

**Comment by codybroyles** [comment] 2019-04-15 14:49
🍅 🍅

**Comment by codybroyles** [comment] 2019-04-15 15:53
:tomato:

**Comment by smattingly** [comment] 2019-04-15 23:38
My latest commit:
1. added testing of `RestController`. Controllers are not part of test coverage calculations because of a setting in the `.nycrc` config file. Even though I am not testing `RestController` and will add more controller tests, the tests don't touch most of the code, because most of the code is calls to model or view stuff that has already been tested. The controller test is just a check that the right HTTP request is going to the right JavaScript function.
2. defined "pending" tests for policies. Many of the tests we were "passing" were actually empty tests; I should have defined those as pending (no function passed to the `it` call). @codybroyles and/or @ricardmc99 can now work on writing those tests for the two policies that have them. I tried to provide enough example to see how it would be done.

**Comment by smattingly** [comment] 2019-04-16 20:42
Pushed another commit that adds kiosk auto logout for students, and "banner" result messages. Right now the banner results are just plain text; I think we should format them something like [this](https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_alerts_success).

BTW, there is some very ugly code coupling in this commit. In particular, the `responseViewSafely` helper has become a kludgy mess. I'm thinking about ways to refactor this.

**Comment by codybroyles** [comment] 2019-04-17 14:32
🍅

**Comment by codybroyles** [comment] 2019-04-17 14:54
🍅

**Comment by codybroyles** [comment] 2019-04-22 19:03
:tomato: Started on completing the policies testing. Having an issue with the redirect test since the student always gets directed to its profile.

**Comment by codybroyles** [comment] 2019-04-24 14:40
🍅

**Comment by codybroyles** [comment] 2019-04-25 21:47
🍅   @smattingly I pushed up the changes to the test data along with the testing filled in. I managed to change back to ``` checkOutTime: { type: "ref", columnType: "datetime" }, ``` while still using null in the database. This removed most of the clutter in the console. I was able to fix a few holes we left open in the policies but there is one test I can't seem to handle if you wouldn't mind looking at it. (See below)

Line332 in https://github.com/dewv/nlcAttendance/blob/Issue33_22_23/test/policies/isAuthorized.js
```   99 passing (6s)
  1 failing

  1) `isAuthorized` policy          
       when the user is authenticated staff
         should forbid requests to update other user profiles:
     Uncaught AssertionError: expected true to be false
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at /home/ubuntu/workspace/nlcAttendance/test/policies/isAuthorized.js:334:43
      at ClientRequest.<anonymous> (test/policies/isAuthorized.js:48:16)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
      at Socket.socketOnData (_http_client.js:447:20)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
```

**Comment by codybroyles** [comment] 2019-04-26 15:13
🍅

**Comment by codybroyles** [comment] 2019-04-26 16:48
🍅

**Comment by codybroyles** [comment] 2019-04-26 17:06
@smattingly  I pushed up the most recent changes which bring our test coverage close to 100% ... with the spreadsheet test uncommented test coverage is 100% for the policies. That leaves just the Helpers test at 90% covered specifically response-view-safely.js which is only at 67% coverage. I am not quite sure about the testing of these calls.

**Comment by codybroyles** [comment] 2019-04-29 14:55
🍅

**Comment by smattingly** [comment] 2019-04-29 21:06
@codybroyles As we discussed, please identify which tests are responsible for the coverage that does exist in that helper, and document findings here. 
The helper was recently extended beyond a simple wrapper to the `ejs.renderFile` call that would respond with 404 when appropriate, using it as a central point to catch all view displays in order to display "result banner" messages. I suspect that we will move to a custom controller that figuratively extends the generic `RestController`, adding a layer to handle `isAppropriate` logic and to handle the results banners. That will probably make for cleaner testing and coverage.

**Comment by codybroyles** [comment] 2019-04-30 02:06
🍅  The tests passing through that helper are the tests for isAuthorized and isAppropriate policies.

**Comment by smattingly** [comment] 2019-09-18 16:15
OBE

**Closed by smattingly** 2019-09-18 16:15 UTC
